const data = [
  {
    id: 1,
    title: "Product 1",
    img: "https://picsum.photos/id/1/1200/1200",
    star: 4.5,
    price: 19.99,
    params: {
      color: ["Red", "Blue", "Green"],
      category: "Category 1",
      geef: "geef",
      dasda: "dasda",
      firm: "Puma",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "John", date: "2022-01-01" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Jane", date: "2022-01-02" },
    ],
  },
  {
    id: 2,
    title: "Product 2",
    img: "https://picsum.photos/id/2/1200/1200",
    star: 3.8,
    price: 12.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Mike", date: "2022-01-03" },
      { id: 2, rating: 4, comment: "Good value for money.", name: "Sarah", date: "2022-01-04" },
    ],
  },
  {
    id: 3,
    title: "Product 3",
    img: "https://picsum.photos/id/3/1200/1200",
    star: 4.2,
    price: 15.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm : "Adidas",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing product!", name: "David", date: "2022-01-05" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Emily", date: "2022-01-06" },
    ],
  },
  {
    id: 4,
    title: "Product 4",
    img: "https://picsum.photos/id/4/1200/1200",
    star: 4.0,
    price: 9.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm : "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Michael", date: "2022-01-07" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Jessica", date: "2022-01-08" },
    ],
  },
  // Add 16 more objects
  {
    id: 5,
    title: "Product 5",
    img: "https://picsum.photos/id/5/1200/1200",
    star: 4.3,
    price: 14.99,
    params: {
      color: "Purple",
      category: "Category 1",
      firm : "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Robert", date: "2022-01-09" },
      { id: 2, rating: 4, comment: "Great value!", name: "Olivia", date: "2022-01-10" },
    ],
  },
  {
    id: 6,
    title: "Product 6",
    img: "https://picsum.photos/id/6/1200/1200",
    star: 3.7,
    price: 11.99,
    params: {
      color: "Orange",
      category: "Category 2",
      firm : "New Balance",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "William", date: "2022-01-11" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Sophia", date: "2022-01-12" },
    ],
  },
  {
    id: 7,
    title: "Product 7",
    img: "https://picsum.photos/id/7/1200/1200",
    star: 4.4,
    price: 16.99,
    params: {
      color: "Pink",
      category: "Category 1",
      firm : "Under Armour",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Fantastic product!", name: "James", date: "2022-01-13" },
      { id: 2, rating: 4, comment: "Great quality!", name: "Ava", date: "2022-01-14" },
    ],
  },
  {
    id: 8,
    title: "Product 8",
    img: "https://picsum.photos/id/8/1200/1200",
    star: 3.9,
    price: 13.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm : "Kappa",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-01-15" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-01-16" },
    ],
  },
  {
    id: 9,
    title: "Product 9",
    img: "https://picsum.photos/id/9/1200/1200",
    star: 4.7,
    price: 21.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm : "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-01-17" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-01-18" },
    ],
  },
  {
    id: 10,
    title: "Product 10",
    img: "https://picsum.photos/id/10/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "White",
      category: "Category 2",
      firm : "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-01-19" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-01-20" },
    ],
  },
  {
    id: 11,
    title: "Product 11",
    img: "https://picsum.photos/id/11/1200/1200",
    star: 4.6,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 1",
      firm : "Vans",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-01-21" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-01-22" },
    ],
  },
  {
    id: 12,
    title: "Product 12",
    img: "https://picsum.photos/id/12/1200/1200",
    star: 3.8,
    price: 15.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm : "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "Matthew", date: "2022-01-23" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Lily", date: "2022-01-24" },
    ],
  },
  {
    id: 13,
    title: "Product 13",
    img: "https://picsum.photos/id/13/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm : "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-01-25" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-01-26" },
    ],
  },
  {
    id: 14,
    title: "Product 14",
    img: "https://picsum.photos/id/14/1200/1200",
    star: 3.7,
    price: 12.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm : "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Andrew", date: "2022-01-27" },
      { id: 2, rating: 4, comment: "Good value for money.", name: "Zoe", date: "2022-01-28" },
    ],
  },
  {
    id: 15,
    title: "Product 15",
    img: "https://picsum.photos/id/15/1200/1200",
    star: 4.2,
    price: 15.99,
    params: {
      color: "Purple",
      category: "Category 1",
      firm : "Zara",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing product!", name: "Ryan", date: "2022-01-29" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Victoria", date: "2022-01-30" },
    ],
  },
  {
    id: 16,
    title: "Product 16",
    img: "https://picsum.photos/id/16/1200/1200",
    star: 4.0,
    price: 9.99,
    params: {
      color: "Orange",
      category: "Category 2",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "John", date: "2022-01-31" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Emma", date: "2022-02-01" },
    ],
  },
  {
    id: 17,
    title: "Product 17",
    img: "https://picsum.photos/id/17/1200/1200",
    star: 4.3,
    price: 14.99,
    params: {
      color: "Pink",
      category: "Category 1",
      firm : "Filla",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "David", date: "2022-02-02" },
      { id: 2, rating: 4, comment: "Great value!", name: "Olivia", date: "2022-02-03" },
    ],
  },
  {
    id: 18,
    title: "Product 18",
    img: "https://picsum.photos/id/18/1200/1200",
    star: 3.7,
    price: 11.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm : "Mango",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "William", date: "2022-02-04" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Sophia", date: "2022-02-05" },
    ],
  },
  {
    id: 19,
    title: "Product 19",
    img: "https://picsum.photos/id/19/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm : "Asics",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good buy!", name: "Benjamin", date: "2022-02-06" },
      { id: 2, rating: 5, comment: "Impressive!", name: "Mia", date: "2022-02-07" },
    ],
  },
  // ...
  {
    id: 20,
    title: "Product 20",
    img: "https://picsum.photos/id/20/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Black",
      category: "Category 1",
      firm : "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good buy!", name: "Daniel", date: "2022-02-08" },
      { id: 2, rating: 5, comment: "Impressive!", name: "Harper", date: "2022-02-09" },
    ],
  },
];

export default data;
