const data = [
  {
    id: 1,
    title: "Product 1",
    img: "https://picsum.photos/id/1/1200/1200",
    star: 4.5,
    price: 19.99,
    params: {
      color: ["Red", "Blue", "Green"],
      category: "Category 1",
      geef: "geef",
      dasda: "dasda",
      firm: "Puma",
      availability: "In Stock",
      size: ["S", "M", "L", "XL", "XXL"],
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "John", date: "2022-01-01" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Jane", date: "2022-01-02" },
    ],
    author: "David"
  },
  {
    id: 2,
    title: "Product 2",
    img: "https://picsum.photos/id/2/1200/1200",
    star: 3.8,
    price: 12.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Mike", date: "2022-01-03" },
      { id: 2, rating: 4, comment: "Good value for money.", name: "Sarah", date: "2022-01-04" },
    ],
  },
  {
    id: 3,
    title: "Product 3",
    img: "https://picsum.photos/id/3/1200/1200",
    star: 4.2,
    price: 15.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm : "Adidas",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing product!", name: "David", date: "2022-01-05" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Emily", date: "2022-01-06" },
    ],
  },
  {
    id: 4,
    title: "Product 4",
    img: "https://picsum.photos/id/4/1200/1200",
    star: 4.0,
    price: 9.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm : "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Michael", date: "2022-01-07" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Jessica", date: "2022-01-08" },
    ],
  },
  // Add 16 more objects
  {
    id: 5,
    title: "Product 5",
    img: "https://picsum.photos/id/5/1200/1200",
    star: 4.3,
    price: 14.99,
    params: {
      color: "Purple",
      category: "Category 1",
      firm : "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Robert", date: "2022-01-09" },
      { id: 2, rating: 4, comment: "Great value!", name: "Olivia", date: "2022-01-10" },
    ],
  },
  {
    id: 6,
    title: "Product 6",
    img: "https://picsum.photos/id/6/1200/1200",
    star: 3.7,
    price: 11.99,
    params: {
      color: "Orange",
      category: "Category 2",
      firm : "New Balance",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "William", date: "2022-01-11" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Sophia", date: "2022-01-12" },
    ],
  },
  {
    id: 7,
    title: "Product 7",
    img: "https://picsum.photos/id/7/1200/1200",
    star: 4.4,
    price: 16.99,
    params: {
      color: "Pink",
      category: "Category 1",
      firm : "Under Armour",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Fantastic product!", name: "James", date: "2022-01-13" },
      { id: 2, rating: 4, comment: "Great quality!", name: "Ava", date: "2022-01-14" },
    ],
  },
  {
    id: 8,
    title: "Product 8",
    img: "https://picsum.photos/id/8/1200/1200",
    star: 3.9,
    price: 13.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm : "Kappa",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-01-15" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-01-16" },
    ],
  },
  {
    id: 9,
    title: "Product 9",
    img: "https://picsum.photos/id/9/1200/1200",
    star: 4.7,
    price: 21.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm : "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-01-17" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-01-18" },
    ],
  },
  {
    id: 10,
    title: "Product 10",
    img: "https://picsum.photos/id/10/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "White",
      category: "Category 2",
      firm : "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-01-19" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-01-20" },
    ],
  },
  {
    id: 11,
    title: "Product 11",
    img: "https://picsum.photos/id/11/1200/1200",
    star: 4.6,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 1",
      firm : "Vans",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-01-21" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-01-22" },
    ],
  },
  {
    id: 12,
    title: "Product 12",
    img: "https://picsum.photos/id/12/1200/1200",
    star: 3.8,
    price: 15.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm : "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "Matthew", date: "2022-01-23" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Lily", date: "2022-01-24" },
    ],
  },
  {
    id: 13,
    title: "Product 13",
    img: "https://picsum.photos/id/13/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm : "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-01-25" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-01-26" },
    ],
  },
  {
    id: 14,
    title: "Product 14",
    img: "https://picsum.photos/id/14/1200/1200",
    star: 3.7,
    price: 12.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm : "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Andrew", date: "2022-01-27" },
      { id: 2, rating: 4, comment: "Good value for money.", name: "Zoe", date: "2022-01-28" },
    ],
  },
  {
    id: 15,
    title: "Product 15",
    img: "https://picsum.photos/id/15/1200/1200",
    star: 4.2,
    price: 15.99,
    params: {
      color: "Purple",
      category: "Category 1",
      firm : "Zara",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing product!", name: "Ryan", date: "2022-01-29" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Victoria", date: "2022-01-30" },
    ],
  },
  {
    id: 16,
    title: "Product 16",
    img: "https://picsum.photos/id/16/1200/1200",
    star: 4.0,
    price: 9.99,
    params: {
      color: "Orange",
      category: "Category 2",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "John", date: "2022-01-31" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Emma", date: "2022-02-01" },
    ],
  },
  {
    id: 17,
    title: "Product 17",
    img: "https://picsum.photos/id/17/1200/1200",
    star: 4.3,
    price: 14.99,
    params: {
      color: "Pink",
      category: "Category 1",
      firm : "Filla",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "David", date: "2022-02-02" },
      { id: 2, rating: 4, comment: "Great value!", name: "Olivia", date: "2022-02-03" },
    ],
  },
  {
    id: 18,
    title: "Product 18",
    img: "https://picsum.photos/id/18/1200/1200",
    star: 3.7,
    price: 11.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm : "Mango",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "William", date: "2022-02-04" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Sophia", date: "2022-02-05" },
    ],
  },
  {
    id: 19,
    title: "Product 19",
    img: "https://picsum.photos/id/19/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm : "Asics",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good buy!", name: "Benjamin", date: "2022-02-06" },
      { id: 2, rating: 5, comment: "Impressive!", name: "Mia", date: "2022-02-07" },
    ],
  },
  // ...
  {
    id: 20,
    title: "Product 20",
    img: "https://picsum.photos/id/20/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Black",
      category: "Category 1",
      firm : "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good buy!", name: "Daniel", date: "2022-02-08" },
      { id: 2, rating: 5, comment: "Impressive!", name: "Harper", date: "2022-02-09" },
    ],
  },
  {
    id: 21,
    title: "Product 21",
    img: "https://picsum.photos/id/21/1200/1200",
    star: 4.4,
    price: 16.99,
    params: {
      color: "Pink",
      category: "Category 2",
      firm : "Under Armour",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Fantastic product!", name: "James", date: "2022-02-10" },
      { id: 2, rating: 4, comment: "Great quality!", name: "Ava", date: "2022-02-11" },
    ],
  },
  {
    id: 22,
    title: "Product 22",
    img: "https://picsum.photos/id/22/1200/1200",
    star: 3.9,
    price: 13.99,
    params: {
      color: "Gray",
      category: "Category 1",
      firm : "Kappa",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-02-12" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-02-13" },
    ],
  },
  // Add more objects from 23 to 40...
  {
    id: 23,
    title: "Product 23",
    img: "https://picsum.photos/id/23/1200/1200",
    star: 4.7,
    price: 21.99,
    params: {
      color: "Brown",
      category: "Category 2",
      firm : "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-02-14" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-02-15" },
    ],
  },
  {
    id: 24,
    title: "Product 24",
    img: "https://picsum.photos/id/24/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "White",
      category: "Category 1",
      firm : "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-02-16" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-02-17" },
    ],
  },
  {
    id: 25,
    title: "Product 25",
    img: "https://picsum.photos/id/25/1200/1200",
    star: 4.6,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 2",
      firm : "Vans",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-02-18" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-02-19" },
    ],
  },
  {
    id: 26,
    title: "Product 26",
    img: "https://picsum.photos/id/26/1200/1200",
    star: 3.8,
    price: 15.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm : "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "Matthew", date: "2022-02-20" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Lily", date: "2022-02-21" },
    ],
  },
  {
    id: 27,
    title: "Product 27",
    img: "https://picsum.photos/id/27/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm : "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-02-22" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-02-23" },
    ],
  },
  {
    id: 28,
    title: "Product 28",
    img: "https://picsum.photos/id/28/1200/1200",
    star: 3.7,
    price: 12.99,
    params: {
      color: "Yellow",
      category: "Category 1",
      firm : "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Andrew", date: "2022-02-24" },
      { id: 2, rating: 4, comment: "Good value for money.", name: "Zoe", date: "2022-02-25" },
    ],
  },
  {
    id: 29,
    title: "Product 29",
    img: "https://picsum.photos/id/29/1200/1200",
    star: 4.2,
    price: 15.99,
    params: {
      color: "Purple",
      category: "Category 2",
      firm : "Zara",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing product!", name: "Ryan", date: "2022-02-26" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Victoria", date: "2022-02-27" },
    ],
  },
  {
    id: 30,
    title: "Product 30",
    img: "https://picsum.photos/id/30/1200/1200",
    star: 4.0,
    price: 9.99,
    params: {
      color: "Orange",
      category: "Category 1",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "John", date: "2022-02-28" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Emma", date: "2022-03-01" },
    ],
  },
  {
    id: 31,
    title: "Product 31",
    img: "https://picsum.photos/id/31/1200/1200",
    star: 4.3,
    price: 14.99,
    params: {
      color: "Pink",
      category: "Category 1",
      firm : "Filla",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "David", date: "2022-03-02" },
      { id: 2, rating: 4, comment: "Great value!", name: "Olivia", date: "2022-03-03" },
    ],
  },
  {
    id: 32,
    title: "Product 32",
    img: "https://picsum.photos/id/32/1200/1200",
    star: 3.7,
    price: 11.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm : "Mango",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "William", date: "2022-03-04" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Sophia", date: "2022-03-05" },
    ],
  },
  {
    id: 33,
    title: "Product 33",
    img: "https://picsum.photos/id/33/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm : "Asics",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good buy!", name: "Benjamin", date: "2022-03-06" },
      { id: 2, rating: 5, comment: "Impressive!", name: "Mia", date: "2022-03-07" },
    ],
  },
  {
    id: 34,
    title: "Product 34",
    img: "https://picsum.photos/id/34/1200/1200",
    star: 4.4,
    price: 16.99,
    params: {
      color: "Black",
      category: "Category 2",
      firm : "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Fantastic product!", name: "Daniel", date: "2022-03-08" },
      { id: 2, rating: 4, comment: "Great quality!", name: "Harper", date: "2022-03-09" },
    ],
  },
  {
    id: 35,
    title: "Product 35",
    img: "https://picsum.photos/id/35/1200/1200",
    star: 3.9,
    price: 13.99,
    params: {
      color: "Gray",
      category: "Category 1",
      firm : "Kappa",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-03-10" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-03-11" },
    ],
  },
  {
    id: 36,
    title: "Product 36",
    img: "https://picsum.photos/id/36/1200/1200",
    star: 4.7,
    price: 21.99,
    params: {
      color: "Brown",
      category: "Category 2",
      firm : "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-03-12" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-03-13" },
    ],
  },
  {
    id: 37,
    title: "Product 37",
    img: "https://picsum.photos/id/37/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "White",
      category: "Category 1",
      firm : "Quiksilver",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-03-14" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-03-15" },
    ],
  },
  {
    id: 38,
    title: "Product 38",
    img: "https://picsum.photos/id/38/1200/1200",
    star: 4.6,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 2",
      firm : "Vans",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-03-16" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-03-17" },
    ],
  },
  {
    id: 39,
    title: "Product 39",
    img: "https://picsum.photos/id/39/1200/1200",
    star: 3.8,
    price: 15.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm : "Adidas",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Not bad.", name: "Matthew", date: "2022-03-18" },
      { id: 2, rating: 2, comment: "Could be better.", name: "Lily", date: "2022-03-19" },
    ],
  },
  {
    id: 40,
    title: "Product 40",
    img: "https://picsum.photos/id/40/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm : "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-03-20" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-03-21" },
    ],
  },
  {
    id: 41,
    title: "Product 41",
    img: "https://picsum.photos/id/41/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 1",
      firm: "Puma",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-03-22" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-03-23" },
    ],
  },
  // Add more objects here...
  {
    id: 42,
    title: "Product 42",
    img: "https://picsum.photos/id/42/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm: "Adidas",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-03-24" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-03-25" },
    ],
  },
  {
    id: 43,
    title: "Product 43",
    img: "https://picsum.photos/id/43/1200/1200",
    star: 4.4,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 1",
      firm: "Vans",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-03-26" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-03-27" },
    ],
  },
  {
    id: 44,
    title: "Product 44",
    img: "https://picsum.photos/id/44/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "White",
      category: "Category 2",
      firm: "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-03-28" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-03-29" },
    ],
  },
  {
    id: 45,
    title: "Product 45",
    img: "https://picsum.photos/id/45/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "Black",
      category: "Category 1",
      firm: "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-03-30" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-03-31" },
    ],
  },
  {
    id: 46,
    title: "Product 46",
    img: "https://picsum.photos/id/46/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm: "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-04-01" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-04-02" },
    ],
  },
  {
    id: 47,
    title: "Product 47",
    img: "https://picsum.photos/id/47/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Yellow",
      category: "Category 1",
      firm: "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-04-03" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-04-04" },
    ],
  },
  {
    id: 48,
    title: "Product 48",
    img: "https://picsum.photos/id/48/1200/1200",
    star: 4.4,
    price: 20.99,
    params: {
      color: "Blue",
      category: "Category 2",
      firm: "Adidas",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-04-05" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-04-06" },
    ],
  },
  {
    id: 49,
    title: "Product 49",
    img: "https://picsum.photos/id/49/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "Red",
      category: "Category 1",
      firm: "Vans",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-04-07" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-04-08" },
    ],
  },
  {
    id: 50,
    title: "Product 50",
    img: "https://picsum.photos/id/50/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "White",
      category: "Category 2",
      firm: "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-04-09" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-04-10" },
    ],
  },
  {
    id: 51,
    title: "Product 51",
    img: "https://picsum.photos/id/51/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm: "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-04-11" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-04-12" },
    ],
  },
  {
    id: 52,
    title: "Product 52",
    img: "https://picsum.photos/id/52/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm: "Puma",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-04-13" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-04-14" },
    ],
  },
  {
    id: 53,
    title: "Product 53",
    img: "https://picsum.photos/id/53/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm: "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-04-15" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-04-16" },
    ],
  },
  {
    id: 54,
    title: "Product 54",
    img: "https://picsum.photos/id/54/1200/1200",
    star: 4.4,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 2",
      firm: "Vans",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-04-17" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-04-18" },
    ],
  },
  {
    id: 55,
    title: "Product 55",
    img: "https://picsum.photos/id/55/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "White",
      category: "Category 1",
      firm: "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-04-19" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-04-20" },
    ],
  },
  {
    id: 56,
    title: "Product 56",
    img: "https://picsum.photos/id/56/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "Black",
      category: "Category 2",
      firm: "Quiksilver",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-04-21" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-04-22" },
    ],
  },
  {
    id: 57,
    title: "Product 57",
    img: "https://picsum.photos/id/57/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm: "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-04-23" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-04-24" },
    ],
  },
  {
    id: 58,
    title: "Product 58",
    img: "https://picsum.photos/id/58/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm: "Puma",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-04-25" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-04-26" },
    ],
  },
  {
    id: 59,
    title: "Product 59",
    img: "https://picsum.photos/id/59/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm: "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-04-27" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-04-28" },
    ],
  },
  {
    id: 60,
    title: "Product 60",
    img: "https://picsum.photos/id/60/1200/1200",
    star: 4.4,
    price: 20.99,
    params: {
      color: "Red",
      category: "Category 2",
      firm: "Vans",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Awesome product!", name: "Alexander", date: "2022-04-29" },
      { id: 2, rating: 4, comment: "Great value!", name: "Ella", date: "2022-04-30" },
    ],
  },
  {
    id: 61,
    title: "Product 61",
    img: "https://picsum.photos/id/61/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "White",
      category: "Category 1",
      firm: "Reebok",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-05-01" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-05-02" },
    ],
  },
  {
    id: 62,
    title: "Product 62",
    img: "https://picsum.photos/id/62/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "Black",
      category: "Category 2",
      firm: "Quiksilver",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-05-03" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-05-04" },
    ],
  },
  {
    id: 63,
    title: "Product 63",
    img: "https://picsum.photos/id/63/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 1",
      firm: "Nike",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-05-05" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-05-06" },
    ],
  },
  {
    id: 64,
    title: "Product 64",
    img: "https://picsum.photos/id/64/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 2",
      firm: "Puma",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-05-07" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-05-08" },
    ],
  },
  {
    id: 65,
    title: "Product 65",
    img: "https://picsum.photos/id/65/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm: "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-05-09" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-05-10" },
    ],
  },
  {
    id: 66,
    title: "Product 66",
    img: "https://picsum.photos/id/66/1200/1200",
    star: 4.5,
    price: 21.99,
    params: {
      color: "Red",
      category: "Category 2",
      firm: "Converse",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Great product!", name: "Liam", date: "2022-05-11" },
      { id: 2, rating: 4, comment: "Highly recommended!", name: "Ava", date: "2022-05-12" },
    ],
  },
  {
    id: 67,
    title: "Product 67",
    img: "https://picsum.photos/id/67/1200/1200",
    star: 4.7,
    price: 23.99,
    params: {
      color: "Purple",
      category: "Category 1",
      firm: "New Balance",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Noah", date: "2022-05-13" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Emma", date: "2022-05-14" },
    ],
  },
  {
    id: 68,
    title: "Product 68",
    img: "https://picsum.photos/id/68/1200/1200",
    star: 4.9,
    price: 25.99,
    params: {
      color: "Orange",
      category: "Category 2",
      firm: "Under Armour",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Liam", date: "2022-05-15" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Olivia", date: "2022-05-16" },
    ],
  },
  {
    id: 69,
    title: "Product 69",
    img: "https://picsum.photos/id/69/1200/1200",
    star: 4.4,
    price: 20.99,
    params: {
      color: "Brown",
      category: "Category 1",
      firm: "Skechers",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Noah", date: "2022-05-17" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Isabella", date: "2022-05-18" },
    ],
  },
  {
    id: 70,
    title: "Product 70",
    img: "https://picsum.photos/id/70/1200/1200",
    star: 4.0,
    price: 16.99,
    params: {
      color: "Gray",
      category: "Category 2",
      firm: "Fila",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Liam", date: "2022-05-19" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-05-20" },
    ],
  },
  {
    id: 71,
    title: "Product 71",
    img: "https://picsum.photos/id/71/1200/1200",
    star: 4.2,
    price: 18.99,
    params: {
      color: "Blue",
      category: "Category 1",
      firm: "Adidas",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Good product.", name: "Daniel", date: "2022-05-21" },
      { id: 2, rating: 3, comment: "Decent quality.", name: "Harper", date: "2022-05-22" },
    ],
  },
  {
    id: 72,
    title: "Product 72",
    img: "https://picsum.photos/id/72/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm: "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-05-23" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-05-24" },
    ],
  },
  {
    id: 73,
    title: "Product 73",
    img: "https://picsum.photos/id/73/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 1",
      firm: "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-05-25" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-05-26" },
    ],
  },
  {
    id: 74,
    title: "Product 74",
    img: "https://picsum.photos/id/74/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "White",
      category: "Category 2",
      firm: "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-05-27" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-05-28" },
    ],
  },
  {
    id: 75,
    title: "Product 75",
    img: "https://picsum.photos/id/75/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "Black",
      category: "Category 1",
      firm: "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-05-29" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-05-30" },
    ],
  },
  {
    id: 76,
    title: "Product 76",
    img: "https://picsum.photos/id/76/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm: "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-05-31" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-06-01" },
    ],
  },
  {
    id: 77,
    title: "Product 77",
    img: "https://picsum.photos/id/77/1200/1200",
    star: 4.1,
    price: 17.99,
    params: {
      color: "Yellow",
      category: "Category 1",
      firm: "Puma",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 3, comment: "Average product.", name: "Oliver", date: "2022-06-02" },
      { id: 2, rating: 4, comment: "Satisfied with the purchase.", name: "Sophia", date: "2022-06-03" },
    ],
  },
  {
    id: 78,
    title: "Product 78",
    img: "https://picsum.photos/id/78/1200/1200",
    star: 4.6,
    price: 22.99,
    params: {
      color: "White",
      category: "Category 2",
      firm: "Reebok",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Nice product.", name: "Benjamin", date: "2022-06-04" },
      { id: 2, rating: 3, comment: "Decent value.", name: "Mia", date: "2022-06-05" },
    ],
  },
  {
    id: 79,
    title: "Product 79",
    img: "https://picsum.photos/id/79/1200/1200",
    star: 4.8,
    price: 24.99,
    params: {
      color: "Black",
      category: "Category 1",
      firm: "Quiksilver",
      availability: "Out of Stock",
    },
    reviews: [
      { id: 1, rating: 5, comment: "Amazing quality!", name: "Ethan", date: "2022-06-06" },
      { id: 2, rating: 4, comment: "Highly satisfied!", name: "Charlotte", date: "2022-06-07" },
    ],
  },
  {
    id: 80,
    title: "Product 80",
    img: "https://picsum.photos/id/80/1200/1200",
    star: 4.3,
    price: 19.99,
    params: {
      color: "Green",
      category: "Category 2",
      firm: "Nike",
      availability: "In Stock",
    },
    reviews: [
      { id: 1, rating: 4, comment: "Great product!", name: "Christopher", date: "2022-06-08" },
      { id: 2, rating: 5, comment: "Excellent quality!", name: "Grace", date: "2022-06-09" },
    ],
  },
];

for (let i = 0; i< data.length; i++){
  data[i].shortDesc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed ante justo. Integer euismod libero id mauris malesuada tincidunt."
  data[i].longDesc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed ante justo. Integer euismod libero id mauris malesuada tincidunt. Vivamus commodo nulla ut lorem rhoncus aliquet. Duis dapibus augue vel ipsum pretium, et venenatis sem blandit. Quisque ut erat vitae nisi ultrices placerat non eget velit. Integer ornare mi sed ipsum lacinia, non sagittis mauris blandit. Morbi fermentum libero vel nisl suscipit, nec tincidunt mi consectetur."
  data[i].params.size = ["S", "M", "L", "XL", "XXL"]
  data[i].author = "David"
}

export default data;
